weight=10 #int | default: 10
min=1 #int | default: 1
max=3 #int | default: 3
biomes=savanna,savanna_plateau,windswept_savanna #String | default: savanna,savanna_plateau,windswept_savanna
is_always_persistent=true #boolean | default: true
check_area_size_for_mobs_of_same_type_when_spawning=16 #int | default: 16
max_mob_number_of_same_type_around_area_when_spawning=3 #int | default: 3
sound_volume=0.3 #float | default: 0.3
play_sound_distance=20 #int | default: 20
idle_sound_minimum_interval=20 #int | default: 20
random_attack_chance=1000 #int | default: 1000
enable_behavior_chat_messages=true #boolean | default: true

